[package]
name = "systemstat"
version = "0.1.2"
authors = [ "Greg V <greg@unrelenting.technology>" ]
keywords = [ "System", "Info" ]
description = "systemstat"
license = "Unlicense"
readme = "README.md"
homepage = "https://github.com/myfreeweb/systemstat"
repository = "https://github.com/myfreeweb/systemstat"

[dependencies]
libc = "0.2"
time = "0.1"
chrono = "0.4"
lazy_static = "0.2"
bytesize = "0.1"
